# Crime and Commercial Presence: Exploring Violent Crime in London

## Preparation

- [Github link](https://github.com/jyjylow/casa0006-assessment)

- Number of words: ***

- Runtime: *** hours (*Memory 10 GB, CPU Intel i7-10700 CPU @2.90GHz*)

- Coding environment: SDS Docker (or anything else)

- License: this notebook is made available under the [Creative Commons Attribution license](https://creativecommons.org/licenses/by/4.0/) (or other license that you like).

- Additional library *[libraries not included in SDS Docker or not used in this module]*:
    - **watermark**: A Jupyter Notebook extension for printing timestamps, version numbers, and hardware information.
    - ......

In [3]:
# importing libraries

# for reading data remotely
import requests
from io import StringIO
import osmnx as ox

# for analysis
import numpy as np
import pandas as pd
import geopandas as gpd
import matplotlib.pyplot as plt 
from sklearn.neighbors import NearestNeighbors
from sklearn.cluster import KMeans, DBSCAN, OPTICS, AgglomerativeClustering
from esda.adbscan import ADBSCAN

## Table of contents

1. [Introduction](#Introduction)

1. [Research questions](#Research-questions)

1. [Data](#Data)

1. [Methodology](#Methodology)

1. [Results and discussion](#Results-and-discussion)

1. [Conclusion](#Conclusion)

1. [References](#References)

# Introduction
[[ Back to top ]](#Table-of-contents)

## Residential vs nonresidential land use and crime
The study of crime and urban land use has given rise to different takes regarding the impacts of residential and nonresidential activity on neighbourhood crime rates. Theorists like Jane Jacobs are optimistic about the advantages of mixed land use, conferring the benefits of dispersing street activity, increasing "eyes on the street"-style social monitoring and control, and bolstering neighbourhood trust (Jacobs, 1961), all factors that can reduce the risk of crime. On the other hand, other approaches (e.g. Taylor, 1988) have associated the mixing of the residential and commercial with a heightened sense of anonymity and decreased territoriality and collective responsibility, thus increasing the propensity for crime. The latter position has contributed to general assumptions that residential land use exerts protective effects on crime, while nonresidential land use exacerbates it (Wo & Kim, 2020). 

To what extent, however, is this assumption a simplistic take on the relationship between crime and land use? Investigating the relationship between land use and crime in the context of Columbus, Ohio, Browning et al. (2010) found that this relationship is indeed nonlinear: while violent crime increased with commercial/residential density at low levels, it in fact decreased past when mixed land use increased beyond a threshold (except robbery). Similarly, Wo and Kim's (2020) study of residential versus nonresidential land use in San Francisco found a positive association between crime rates and retail/commercial mixed-use areas, but found also that nonresidential land use exhibited non-significant and inconclusive associations with increased crime. In other words, nonresidential land use cannot always be associated with higher crime (Stucky & Ottensmann, 2009), demonstrating the limitations of a binary understanding of residential/nonresidential land use and crime.

## Research questions
[[ Back to top ]](#Table-of-contents)

This study aims to investigate the nuanced relationship between land use and crime in London's context, with a particular focus on violent, person-to-person crime. As such, my research questions are as follows:

1. What is the spatial distribution of violent crime in London, and how does this correlate to residential/nonresidential land use characteristics?
2.

## Data
[[ Back to top ]](#Table-of-contents)

### 1. Violent crime data

In [25]:
# reading in data from github repository
crimeurl = "https://raw.githubusercontent.com/jyjylow/casa0006-assessment/refs/heads/main/data/MPS%20Ward%20Level%20Crime%20(Historical).csv"
response = requests.get(crimeurl)
if response.status_code == 200:
    data = StringIO(response.text)
    crimedf = pd.read_csv(data)
    print("Ward-level crime data loaded successfully.")
else:
    print(f"Failed to fetch the file: {response.status_code}")

# peeking at crime data
crimedf.head()

Ward-level crime data loaded successfully.

,WardName,WardCode,MajorText,MinorText,LookUp_BoroughName,201004,201005,201006,201007,201008,...,202112,202201,202202,202203,202204,202205,202206,202207,202208,202209
0,Heathrow Villages,E05013570,ARSON AND CRIMINAL DAMAGE,CRIMINAL DAMAGE,Aviation Security (SO18),0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,Heathrow Villages,E05013570,MISCELLANEOUS CRIMES AGAINST SOCIETY,MISC CRIMES AGAINST SOCIETY,Aviation Security (SO18),0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,Heathrow Villages,E05013570,THEFT,OTHER THEFT,Aviation Security (SO18),0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,Heathrow Villages,E05013570,THEFT,SHOPLIFTING,Aviation Security (SO18),0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,Heathrow Villages,E05013570,VEHICLE OFFENCES,THEFT FROM A VEHICLE,Aviation Security (SO18),0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [41]:
# understanding the categories of crime reports
print(f"Counts of reports by major crime category:")
print(crimedf.MajorText.value_counts().reset_index())

Counts of reports by major crime category:
                               MajorText  count
0                                  THEFT   2718
1                       VEHICLE OFFENCES   2717
2                  PUBLIC ORDER OFFENCES   2432
3            VIOLENCE AGAINST THE PERSON   1902
4              ARSON AND CRIMINAL DAMAGE   1359
5                               BURGLARY   1358
6                          DRUG OFFENCES   1358
7                                ROBBERY   1358
8                        SEXUAL OFFENCES   1358
9   MISCELLANEOUS CRIMES AGAINST SOCIETY    680
10                     FRAUD AND FORGERY    679
11                 POSSESSION OF WEAPONS    679

Clearly, "VIOLENCE AGAINST THE PERSON" reports are relevant to my study. Other categories might also be pertinent, so I'm taking a look at the subcategories so I don't miss out on important reports.

In [44]:
# displaying main and subcategories of crime reports in a table
crime_categories = crimedf[["MajorText", "MinorText"]].drop_duplicates().sort_values(["MajorText", "MinorText"]).reset_index(drop=True)
crime_categories

,MajorText,MinorText
0,ARSON AND CRIMINAL DAMAGE,ARSON
1,ARSON AND CRIMINAL DAMAGE,CRIMINAL DAMAGE
2,BURGLARY,BURGLARY BUSINESS AND COMMUNITY
3,BURGLARY,BURGLARY IN A DWELLING
4,DRUG OFFENCES,POSSESSION OF DRUGS
5,DRUG OFFENCES,TRAFFICKING OF DRUGS
6,FRAUD AND FORGERY,FRAUD AND FORGERY
7,MISCELLANEOUS CRIMES AGAINST SOCIETY,MISC CRIMES AGAINST SOCIETY
8,POSSESSION OF WEAPONS,POSSESSION OF WEAPONS
9,PUBLIC ORDER OFFENCES,OTHER OFFENCES PUBLIC ORDER
10,PUBLIC ORDER OFFENCES,PUBLIC FEAR ALARM OR DISTRESS
11,PUBLIC ORDER OFFENCES,RACE OR RELIGIOUS AGG PUBLIC FEAR
12,PUBLIC ORDER OFFENCES,VIOLENT DISORDER
13,ROBBERY,ROBBERY OF BUSINESS PROPERTY
14,ROBBERY,ROBBERY OF PERSONAL PROPERTY
15,SEXUAL OFFENCES,OTHER SEXUAL OFFENCES
16,SEXUAL OFFENCES,RAPE
17,THEFT,BICYCLE THEFT
18,THEFT,OTHER THEFT
19,THEFT,SHOPLIFTING
20,THEFT,THEFT FROM THE PERSON
21,VEHICLE OFFENCES,AGGRAVATED VEHICLE TAKING
22,VEHICLE OFFENCES,INTERFERING WITH A MOTOR VEHICLE
23,VEHICLE OFFENCES,THEFT FROM A VEHICLE
24,VEHICLE OFFENCES,THEFT OR UNAUTH TAKING OF A MOTOR VEH
25,VIOLENCE AGAINST THE PERSON,HOMICIDE
26,VIOLENCE AGAINST THE PERSON,VIOLENCE WITH INJURY
27,VIOLENCE AGAINST THE PERSON,VIOLENCE WITHOUT INJURY

Based on this, I identified that:
- "PUBLIC ORDER OFFENCES: VIOLENT DISORDER"
- "SEXUAL OFFENCES: RAPE"
- "VEHICLE OFFENCES: AGGRAVATED VEHICLE TAKING"

are highly likely to be relevant to my study as they entail a degree of person-to-person physical violence. These will thus be included in analysis.

In [48]:
# filtering crimedf to relevant rows/cols

# 1. excluding "Aviation Security" borough from my area of study
crimedf = crimedf[crimedf.LookUp_BoroughName != "Aviation Security (SO18)"]

# 2. filtering dataset to crimes of "VIOLENCE AGAINST THE PERSON" and the subcategories listed above
crimedf = crimedf[(crimedf.MajorText == "VIOLENCE AGAINST THE PERSON") & 
          crimedf.MinorText.isin(["VIOLENT DISORDER", "RAPE", "AGGRAVATED VEHICLE TAKING"])]

### 2. London geometry

In [ ]:
# reading in London ward boundaries
wardurl = "https://github.com/jyjylow/casa0006-assessment/raw/main/data/London-wards-2018.zip"
response = requests.get(crimeurl)
if response.status_code == 200:
    data = StringIO(response.text)
    crimedf = pd.read_csv(data)
    print("Ward-level crime data loaded successfully.")
else:
    print(f"Failed to fetch the file: {response.status_code}")

url = 'https://github.com/jreades/fsds/raw/master/data/src/Middle_Layer_Super_Output_Areas__December_2011__EW_BGC_V2-shp.zip'
! wget -P data $url

In [ ]:
gdf = gpd.read_file(f"zip://data/Middle_Layer_Super_Output_Areas__December_2011__EW_BGC_V2-shp.zip!Middle_Layer_Super_Output_Areas__December_2011__EW_BGC_V2.shp")
gdf.head()

### 3. OpenStreetMap data on land use

## Methodology
[[ Back to top ]](#Table-of-contents)
- INCLUDE TABLE!

## Results & Discussion
[[ Back to top ]](#Table-of-contents)

## Conclusion
[[ Back to top ]](#Table-of-contents)

## References
[[ Back to top ]](#Table-of-contents)

1. Jacobs, J. (1961). _The Death and Life of Great American Cities_. New York, NY: Random House.

2. Stucky, T. D., & Ottensmann, J. R. (2009). Land use and violent crime. _Criminology_,
47(4), 1223-1264.